###
GET https://localhost:5001/api/Khsds/Services/HS HTTP/1.1

###
GET https://localhost:5001/api/employees/SocialMedia/GetToken/177000/1 HTTP/1.1

###
GET https://localhost:5001/api/employees/SocialMedia/ForWeb/mr HTTP/1.1

###
GET https://localhost:5001/api/khsds/Services/HeadersForWebMenu HTTP/1.1

###
GET https://localhost:5001/api/khsds/Services/GoodFor/M HTTP/1.1

###
GET https://api.kenneths.com/api/appointmentbook/WebMarketingTracking/56/MARKXB HTTP/1.1